spring.application.name=turismoapi
spring.datasource.url=jdbc:postgresql://db:5432/db_comentarios
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

