spring.application.name=turismoapi
spring.datasource.url=jdbc:postgresql://db:5432/db_comentarios
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect:org.hibernate.dialect.PostgresSQLDialect
