### GET request to example server
GET http://localhost:8090/libros/

### GET request to example server
GET http://localhost:8090/libros/1

###
POST http://localhost:8090/libros
Content-Type: application/json

{
  "id":"3",
  "titulo":"Alicia en el país de las maravillas",
  "autor":"Lewis Carrol"
}

###
PUT http://localhost:8090/libros/1
Content-Type: application/json

{
  "titulo":"Alicia maravillas",
  "autor":"Lewis Carrol"
}

###
DELETE http://localhost:8090/libros/1

###
DELETE http://localho