services:
  db:
    image: amazeeiolagoon/postgres-latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: db_comentarios
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: apicomentarios
    ports:
      - "8090:8080"
    depends_on:
      - db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_comentarios
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update