### GET request to example server
GET http://localhost:8090/comentarios
###
POST http://localhost:8090/comentarios
Content-Type: application/json

{
  "contenido": "Este lugar es maravilloso",
  "usuario": "pepelucena",
  "fecha": "20260130"
}